controller_manager:
  ros__parameters:
    update_rate: 2  # Hz

    stretch_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_controller:
      type: joint_state_controller/JointStateController

stretch_controller:
  ros__parameters:
    allow_partial_joints_goal: true
    joints:
      - joint_lift
      - joint_arm_l3
      - joint_arm_l2
      - joint_arm_l1
      - joint_arm_l0
      - joint_wrist_yaw
      - joint_head_pan
      - joint_head_tilt
      - joint_gripper_finger_left
      - joint_gripper_finger_right
